### ISSUE TITLE
您好！请问图片分离完需合成的时候总是提示安装openimageio，但是我brew已经安装了，请问是应该是哪里有问题呢？

### ISSUE THREAD

**Issue by afen261** [m13253/heif-hdrgainmap-decode#1]
在“./heif-hdrgainmap-decode-scrgb.py IMG_0000.heic IMG_0000-urn_com_apple_photo_2020_aux_hdrgainmap.png IMG_0000.exr”这一步时，总是提醒：“Please install OpenImageIO using:
  % brew install openimageio”，但brew已经安装openimageio，请教一下可能是哪里有问题？

**Comment by m13253** [comment]
试试看重装一下，有可能升级了 Python 版本，但没升级 OpenImageIO 的版本。版本不一致导致找不到 OpenImageIO 的路径。
除此之外确认一下你的机器里是否有装多个不同来源的 Python（除了 Homebrew，比如 Apple Developer Tools 或者 Anaconda）。应该使用 Homebrew 的 Python 来执行 `./heif-hdrgainmap-decode-scrgb.py`。
除此之外可以使用 `brew list openimageio | grep python` 来确认 Python 库的版本和路径。

**Comment by afen261** [comment]
非常感谢您的回复，按照您的方式删除了多余版本，重新link了一下可以了。但是就是heif-hdrgainmap-decode-y4m.py这个生成的EXR的图片是打不开，导入photoshop也是出错的，其他两条命令没问题。还有就是想请教一下，是否有编码成avif的方式，因为现在支持avif格式的HDR图片可以在chrome搭配HDR显示设备浏览到HDR效果。

**Comment by m13253** [comment]
Y4M 是 YUV4MPEG 格式，里面是未压缩的 YCbCr 数据，而不是 RGB 数据。
你可以直接使用以下命令把 Y4M 编码成 AVIF 图片：
```
avifenc --cicp 9/16/9 --min 1 --max 12 IMG_0000.y4m IMG_0000.avif
```

但是，这个程序输出的 Y4M 是 12-bit 色彩，很多 AVIF 看图软件只能解码 8-bit 或 10-bit 的图片。
如果你遇到了这样的情况，可以使用 FFmpeg 来把 12-bit Y4M 转换为 10-bit Y4M：
```
ffmpeg -i IMG_0000.y4m -pix_fmt yuv444p10le -strict -1 IMG_0000-10bit.y4m
```
然后再用 `avifenc` 来编码成 AVIF：
```
avifenc --cicp 9/16/9 --min 1 --max 12 IMG_0000-10bit.y4m IMG_0000.avif
```

**Comment by afen261** [comment]
非常感谢您的耐心回复，我尝试一下！
