### ISSUE TITLE
想请问一下，HDR GIAN MAP这个过程可逆吗？

### ISSUE THREAD

**Issue by afen261** [m13253/heif-hdrgainmap-decode#2]
不好意思想再次请教，想请问一下，HDR GIAN MAP这个过程可逆吗？就是之前是分离再合成，现在如果反过来是否可以用其他非iphone拍摄的图片去反过来合成至heic的格式

**Comment by m13253** [comment]
理论上可逆，实际上因为算法没公开所以不可逆。

**Comment by afen261** [comment]
明白，谢谢解答
